version: '3'
services:
  rabbit:
    container_name: rabbit
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
  postgresql:
    container_name: postgresql
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: horusec_db
    volumes:
      - /var/lib/postgres/db/data:/var/lib/postgresql/data
    tty: true
    logging:
      driver: json-file
      options:
        max-size: 10m
  horusec-messages:
    build:
      context: ../
      dockerfile: ./horusec-messages/deployments/Dockerfile
    depends_on:
      - "rabbit"
    restart: always
    container_name: horusec-messages
    ports:
      - "8004:8004"
    environment:
      HORUSEC_BROKER_HOST: rabbit
      HORUSEC_BROKER_PORT: "5672"
      HORUSEC_BROKER_USERNAME: "guest"
      HORUSEC_BROKER_PASSWORD: "guest"
      HORUSEC_SMTP_ADDRESS: "smtp.mailtrap.io"
      HORUSEC_SMTP_USERNAME: ${HORUSEC_SMTP_USERNAME}
      HORUSEC_SMTP_PASSWORD: ${HORUSEC_SMTP_PASSWORD}
      HORUSEC_SMTP_HOST: "smtp.mailtrap.io"
      HORUSEC_SMTP_PORT: "2525"
      HORUSEC_EMAIL_FROM: "horusec@zup.com.br"
  horusec-account:
    build:
      context: ../
      dockerfile: ./horusec-account/deployments/Dockerfile
    depends_on:
      - "rabbit"
      - postgresql
    restart: always
    container_name: horusec-account
    ports:
      - "8003:8003"
    environment:
      HORUSEC_ACCOUNT_DISABLE_EMAIL_SERVICE: "true"
      HORUSEC_BROKER_HOST: rabbit
      HORUSEC_BROKER_PORT: "5672"
      HORUSEC_BROKER_USERNAME: "guest"
      HORUSEC_BROKER_PASSWORD: "guest"
      HORUSEC_DATABASE_SQL_URI: "postgresql://root:root@postgresql:5432/horusec_db?sslmode=disable"
      HORUSEC_DATABASE_SQL_DIALECT: "postgres"
      HORUSEC_JWT_SECRET_KEY: "horusec-secret"
  horusec-analytic:
    build:
      context: ../
      dockerfile: ./horusec-analytic/deployments/Dockerfile
    depends_on:
      - postgresql
    restart: always
    container_name: horusec-analytic
    ports:
      - "8005:8005"
    environment:
      HORUSEC_DATABASE_SQL_URI: "postgresql://root:root@postgresql:5432/horusec_db?sslmode=disable"
      HORUSEC_DATABASE_SQL_DIALECT: "postgres"
  horusec-api:
    build:
      context: ../
      dockerfile: ./horusec-api/deployments/Dockerfile
    depends_on:
      - "rabbit"
      - postgresql
    restart: always
    container_name: horusec-api
    ports:
      - "8000:8000"
    environment:
      HORUSEC_DATABASE_SQL_URI: "postgresql://root:root@postgresql:5432/horusec_db?sslmode=disable"
      HORUSEC_DATABASE_SQL_DIALECT: "postgres"
      HORUSEC_JWT_SECRET_KEY: "horusec-secret"
  horusec-manager:
    build:
      context: ../
      dockerfile: ./horusec-manager/deployments/Dockerfile
    restart: always
    container_name: horusec-manager
    ports:
      - "8043:8080"
    environment:
      REACT_APP_HORUSEC_ENDPOINT_API: ${REACT_APP_HORUSEC_ENDPOINT_API}
      REACT_APP_HORUSEC_ENDPOINT_ANALYTIC: ${REACT_APP_HORUSEC_ENDPOINT_ANALYTIC}
      REACT_APP_HORUSEC_ENDPOINT_ACCOUNT: ${REACT_APP_HORUSEC_ENDPOINT_ACCOUNT}
      REACT_APP_HORUSEC_ENDPOINT_AUTH: ${REACT_APP_HORUSEC_ENDPOINT_AUTH}
