version: '3'
services:
#  ldap-service:
#    container_name: ldap-service
#    image: osixia/openldap:1.1.8
#    ports:
#      - "389:389"
#      - "636:636"
#  ldap-admin:
#    container_name: ldap-admin
#    image: osixia/phpldapadmin:0.9.0
#    ports:
#      - "6443:443"
#    depends_on:
#      - "ldap-service"
#    environment:
#      PHPLDAPADMIN_LDAP_HOSTS: ldap-service
#  postgresql_keycloak:
#    container_name: postgresql_keycloak
#    image: postgres:12
#    ports:
#      - "5433:5433"
#    expose:
#      - "5433"
#    command: -p 5433
#    environment:
#      POSTGRES_PASSWORD: root
#      POSTGRES_USER: root
#      POSTGRES_DB: keycloak
#  keycloak:
#    depends_on:
#      - postgresql_keycloak
#    container_name: keycloak
#    image: jboss/keycloak
#    ports:
#      - "8080:8080"
#    environment:
#      DB_VENDOR: "postgres"
#      DB_ADDR: postgresql_keycloak
#      DB_PORT: "5433"
#      DB_USER: "root"
#      DB_PASSWORD: "root"
#      KEYCLOAK_USER: "keycloak"
#      KEYCLOAK_PASSWORD: "keycloak"
  rabbit:
    container_name: rabbit
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
  postgresql:
    container_name: postgresql
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: horusec_db
    volumes:
      - /var/lib/postgres/db/data:/var/lib/postgresql/data
    tty: true
    logging:
      driver: json-file
      options:
        max-size: 10m
  horusec-messages:
    build:
      context: ../
      dockerfile: ./horusec-messages/deployments/Dockerfile.dev
    depends_on:
      - "rabbit"
    restart: always
    container_name: horusec-messages
    network_mode: "host"
    ports:
      - "8004:8004"
    volumes:
      - ../:/usr/app
    environment:
      HORUSEC_BROKER_HOST: "127.0.0.1"
      HORUSEC_BROKER_PORT: "5672"
      HORUSEC_BROKER_USERNAME: "guest"
      HORUSEC_BROKER_PASSWORD: "guest"
      HORUSEC_SMTP_ADDRESS: "smtp.mailtrap.io"
      HORUSEC_SMTP_USERNAME: ${HORUSEC_SMTP_USERNAME}
      HORUSEC_SMTP_PASSWORD: ${HORUSEC_SMTP_PASSWORD}
      HORUSEC_SMTP_HOST: "smtp.mailtrap.io"
      HORUSEC_SMTP_PORT: "2525"
      HORUSEC_EMAIL_FROM: "horusec@zup.com.br"
  horusec-auth:
    build:
      context: ../
      dockerfile: ./horusec-auth/deployments/Dockerfile.dev
    depends_on:
      - "postgresql"
    restart: always
    container_name: horusec-auth
    network_mode: "host"
    ports:
      - "8006:8006"
      - "8007:8007"
    volumes:
      - ../:/usr/app
    environment:
      HORUSEC_DATABASE_SQL_URI: "postgresql://root:root@127.0.0.1:5432/horusec_db?sslmode=disable"
      HORUSEC_DATABASE_SQL_DIALECT: "postgres"
      HORUSEC_JWT_SECRET_KEY: "horusec-secret"
      HORUSEC_KEYCLOAK_BASE_PATH: "http://127.0.0.1:8080"
      HORUSEC_KEYCLOAK_CLIENT_ID: "account"
      HORUSEC_KEYCLOAK_CLIENT_SECRET: "00000000-0000-0000-0000-000000000000" # Get secret inside of keycloak server
      HORUSEC_KEYCLOAK_REALM: "master"
      HORUS_LDAP_BASE: "dc=example,dc=org"
      HORUS_LDAP_HOST: "127.0.0.1"
      HORUS_LDAP_PORT: "389"
      HORUS_LDAP_USESSL: "false"
      HORUS_LDAP_SKIP_TLS: "true"
      HORUS_LDAP_INSECURE_SKIP_VERIFY: "true"
      HORUS_LDAP_BINDDN: "cn=admin,dc=example,dc=org"
      HORUS_LDAP_BINDPASSWORD: "admin"
      HORUS_LDAP_USERFILTER: "(uid=%s)"
      HORUS_LDAP_GROUPFILTER: "(memberUid=%s)"
      HORUSEC_LDAP_ADMIN_GROUP: "admin"
      HORUSEC_ENABLE_APPLICATION_ADMIN: "false"
      HORUSEC_APPLICATION_ADMIN_DATA: "{\"username\": \"horusec-admin\", \"email\":\"horusec-admin@example.com\", \"password\":\"Devpass0*\"}"
      HORUSEC_AUTH_TYPE: "horusec"
      HORUSEC_BROKER_HOST: "127.0.0.1"
      HORUSEC_BROKER_PORT: "5672"
      HORUSEC_BROKER_USERNAME: "guest"
      HORUSEC_BROKER_PASSWORD: "guest"
      HORUSEC_DISABLED_BROKER: "true"
  horusec-account:
    build:
      context: ../
      dockerfile: ./horusec-account/deployments/Dockerfile.dev
    depends_on:
      - "rabbit"
      - "postgresql"
    restart: always
    container_name: horusec-account
    network_mode: "host"
    ports:
      - "8003:8003"
    volumes:
      - ../:/usr/app
    environment:
      HORUSEC_DISABLED_BROKER: "true"
      HORUSEC_BROKER_HOST: "127.0.0.1"
      HORUSEC_BROKER_PORT: "5672"
      HORUSEC_BROKER_USERNAME: "guest"
      HORUSEC_BROKER_PASSWORD: "guest"
      HORUSEC_DATABASE_SQL_URI: "postgresql://root:root@127.0.0.1:5432/horusec_db?sslmode=disable"
      HORUSEC_DATABASE_SQL_DIALECT: "postgres"
      HORUSEC_AUTH_URL: "127.0.0.1:8007"
  horusec-analytic:
    build:
      context: ../
      dockerfile: ./horusec-analytic/deployments/Dockerfile.dev
    depends_on:
      - "postgresql"
    restart: always
    container_name: horusec-analytic
    network_mode: "host"
    ports:
      - "8005:8005"
    volumes:
      - ../:/usr/app
    environment:
      HORUSEC_DATABASE_SQL_URI: "postgresql://root:root@127.0.0.1:5432/horusec_db?sslmode=disable"
      HORUSEC_DATABASE_SQL_DIALECT: "postgres"
      HORUSEC_AUTH_URL: "127.0.0.1:8007"
  horusec-api:
    build:
      context: ../
      dockerfile: ./horusec-api/deployments/Dockerfile.dev
    depends_on:
      - "rabbit"
      - postgresql
    restart: always
    container_name: horusec-api
    network_mode: "host"
    ports:
      - "8000:8000"
    volumes:
      - ../:/usr/app
    environment:
      HORUSEC_DATABASE_SQL_URI: "postgresql://root:root@127.0.0.1:5432/horusec_db?sslmode=disable"
      HORUSEC_DATABASE_SQL_DIALECT: "postgres"
      HORUSEC_AUTH_URL: "127.0.0.1:8007"
      HORUSEC_DISABLED_BROKER: "true"
      HORUSEC_BROKER_HOST: "127.0.0.1"
      HORUSEC_BROKER_PORT: "5672"
      HORUSEC_BROKER_USERNAME: "guest"
      HORUSEC_BROKER_PASSWORD: "guest"
  horusec-webhook:
    build:
      context: ../
      dockerfile: ./horusec-webhook/deployments/Dockerfile.dev
    depends_on:
      - "rabbit"
      - postgresql
    restart: always
    container_name: horusec-webhook
    network_mode: "host"
    ports:
      - "8008:8008"
    volumes:
      - ../:/usr/app
    environment:
      HORUSEC_DATABASE_SQL_URI: "postgresql://root:root@127.0.0.1:5432/horusec_db?sslmode=disable"
      HORUSEC_DATABASE_SQL_DIALECT: "postgres"
      HORUSEC_AUTH_URL: "127.0.0.1:8007"
      HORUSEC_DISABLED_BROKER: "true"
      HORUSEC_BROKER_HOST: "127.0.0.1"
      HORUSEC_BROKER_PORT: "5672"
      HORUSEC_BROKER_USERNAME: "guest"
      HORUSEC_BROKER_PASSWORD: "guest"
  horusec-manager:
    build:
      context: ../
      dockerfile: ./horusec-manager/deployments/Dockerfile
    restart: always
    container_name: horusec-manager
    ports:
      - "8043:8080"
    volumes:
      - ../:/usr/app
    environment:
      REACT_APP_HORUSEC_ENDPOINT_API: ${REACT_APP_HORUSEC_ENDPOINT_API}
      REACT_APP_HORUSEC_ENDPOINT_ANALYTIC: ${REACT_APP_HORUSEC_ENDPOINT_ANALYTIC}
      REACT_APP_HORUSEC_ENDPOINT_ACCOUNT: ${REACT_APP_HORUSEC_ENDPOINT_ACCOUNT}
      REACT_APP_HORUSEC_ENDPOINT_AUTH: ${REACT_APP_HORUSEC_ENDPOINT_AUTH}
      REACT_APP_KEYCLOAK_BASE_PATH: ${REACT_APP_KEYCLOAK_BASE_PATH}
      REACT_APP_KEYCLOAK_CLIENT_ID: ${REACT_APP_KEYCLOAK_CLIENT_ID}
      REACT_APP_KEYCLOAK_REALM: ${REACT_APP_KEYCLOAK_REALM}
      REACT_APP_MICROFRONTEND_PUBLIC_PATH: ${REACT_APP_MICROFRONTEND_PUBLIC_PATH}
      REACT_APP_HORUSEC_MANAGER_THEME: ${REACT_APP_HORUSEC_MANAGER_THEME}
