version: '3'

services:
  postgresql:
    container_name: postgresql
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: horusec_db
    volumes:
      - /var/lib/postgres/db/data:/var/lib/postgresql/data
    tty: true
    logging:
      driver: json-file
      options:
        max-size: 10m
  postgresql_keycloak:
    container_name: postgresql_keycloak
    image: postgres:12
    ports:
      - "5433:5433"
    expose:
      - "5433"
    command: -p 5433
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: keycloak
  keycloak:
    container_name: keycloak
    image: jboss/keycloak
    ports:
      - "8080:8080"
    network_mode: "host"
    environment:
      DB_VENDOR: "postgres"
      DB_ADDR: "127.0.0.1"
      DB_PORT: "5433"
      DB_USER: "root"
      DB_PASSWORD: "root"
      KEYCLOAK_USER: "keycloak"
      KEYCLOAK_PASSWORD: "keycloak"
  horusec-account:
    build:
      context: ../../
      dockerfile: ./horusec-account/deployments/Dockerfile.dev
    depends_on:
      - postgresql
      - keycloak
    restart: always
    container_name: horusec-account
    ports:
      - "8003:8003"
    network_mode: "host"
    environment:
      HORUSEC_ACCOUNT_DISABLE_EMAIL_SERVICE: "true"
      HORUSEC_DATABASE_SQL_URI: "postgresql://root:root@127.0.0.1:5432/horusec_db?sslmode=disable"
      HORUSEC_DATABASE_SQL_DIALECT: "postgres"
      HORUSEC_AUTH_URL: "127.0.0.1:8007"
  horusec-auth:
    build:
      context: ../../
      dockerfile: ./horusec-auth/deployments/Dockerfile.dev
    depends_on:
      - postgresql
      - keycloak
    restart: always
    container_name: horusec-auth
    ports:
      - "8006:8006"
    network_mode: "host"
    environment:
      HORUSEC_DATABASE_SQL_URI: "postgresql://root:root@127.0.0.1:5432/horusec_db?sslmode=disable"
      HORUSEC_DATABASE_SQL_DIALECT: "postgres"
      HORUSEC_ENABLE_APPLICATION_ADMIN: "false"
      HORUSEC_AUTH_TYPE: "keycloak"
      HORUSEC_KEYCLOAK_BASE_PATH: "http://127.0.0.1:8080"
      HORUSEC_KEYCLOAK_CLIENT_ID: "account"
      HORUSEC_KEYCLOAK_CLIENT_SECRET: ${HORUSEC_KEYCLOAK_CLIENT_SECRET}
      HORUSEC_KEYCLOAK_REALM: "master"
      HORUSEC_KEYCLOAK_OTP: "false"
  horusec-analytic:
    build:
      context: ../../
      dockerfile: ./horusec-analytic/deployments/Dockerfile.dev
    depends_on:
      - postgresql
      - keycloak
    restart: always
    container_name: horusec-analytic
    ports:
      - "8005:8005"
    network_mode: "host"
    environment:
      HORUSEC_DATABASE_SQL_URI: "postgresql://root:root@127.0.0.1:5432/horusec_db?sslmode=disable"
      HORUSEC_DATABASE_SQL_DIALECT: "postgres"
      HORUSEC_AUTH_URL: "127.0.0.1:8007"
