version: '3'
services:
  postgresql:
    container_name: postgresql
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: horusec_db
    volumes:
      - /var/lib/postgres/db/data:/var/lib/postgresql/data
    tty: true
    logging:
      driver: json-file
      options:
        max-size: 10m
  horusec-auth:
    build:
      context: ../../
      dockerfile: ./horusec-auth/deployments/Dockerfile.dev
    depends_on:
      - postgresql
    restart: always
    container_name: horusec-auth
    ports:
      - "8006:8006"
    environment:
      HORUSEC_DATABASE_SQL_URI: "postgresql://root:root@postgresql:5432/horusec_db?sslmode=disable"
      HORUSEC_DATABASE_SQL_DIALECT: "postgres"
      HORUSEC_JWT_SECRET_KEY: "horusec-secret"
      HORUSEC_KEYCLOAK_BASE_PATH: ${HORUSEC_KEYCLOAK_BASE_PATH}
      HORUSEC_KEYCLOAK_CLIENT_ID: ${HORUSEC_KEYCLOAK_CLIENT_ID}
      HORUSEC_KEYCLOAK_CLIENT_SECRET: ${HORUSEC_KEYCLOAK_CLIENT_SECRET}
      HORUSEC_KEYCLOAK_REALM: ${HORUSEC_KEYCLOAK_REALM}
      HORUSEC_ENABLE_APPLICATION_ADMIN: "false"
      HORUSEC_APPLICATION_ADMIN_DATA: "{\"username\": \"horusec-admin\", \"email\":\"horusec-admin@example.com\", \"password\":\"Devpass0*\"}"
      HORUSEC_AUTH_TYPE: "horusec"
      HORUSEC_AUTH_DISABLE_EMAIL_SERVICE: "true"
