version: '3'
services:
  ldap-service:
    container_name: ldap-service
    image: osixia/openldap:1.1.8
    ports:
      - "389:389"
      - "636:636"
  ldap-admin:
    container_name: ldap-admin
    image: osixia/phpldapadmin:0.9.0
    ports:
      - "6443:443"
    depends_on:
      - "ldap-service"
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: ldap-service
  postgresql:
    container_name: postgresql
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: horusec_db
    volumes:
      - /var/lib/postgres/db/data:/var/lib/postgresql/data
    tty: true
    logging:
      driver: json-file
      options:
        max-size: 10m
  horusec-auth:
    build:
      context: ../
      dockerfile: ./horusec-auth/deployments/Dockerfile.dev
    depends_on:
      - postgresql
    restart: always
    container_name: horusec-auth
    ports:
      - "8006:8006"
    environment:
      HORUSEC_DATABASE_SQL_URI: "postgresql://root:root@postgresql:5432/horusec_db?sslmode=disable"
      HORUSEC_DATABASE_SQL_DIALECT: "postgres"
      HORUSEC_JWT_SECRET_KEY: "horusec-secret"
      HORUSEC_KEYCLOAK_BASE_PATH: ${HORUSEC_KEYCLOAK_BASE_PATH}
      HORUSEC_KEYCLOAK_CLIENT_ID: ${HORUSEC_KEYCLOAK_CLIENT_ID}
      HORUSEC_KEYCLOAK_CLIENT_SECRET: ${HORUSEC_KEYCLOAK_CLIENT_SECRET}
      HORUSEC_KEYCLOAK_REALM: ${HORUSEC_KEYCLOAK_REALM}
      HORUS_LDAP_BASE: "dc=example,dc=org"
      HORUS_LDAP_HOST: "ldap-service"
      HORUS_LDAP_PORT: "389"
      HORUS_LDAP_USESSL: "false"
      HORUS_LDAP_SKIP_TLS: "true"
      HORUS_LDAP_INSECURE_SKIP_VERIFY: "true"
      HORUS_LDAP_BINDDN: "cn=admin,dc=example,dc=org"
      HORUS_LDAP_BINDPASSWORD: "admin"
      HORUS_LDAP_USERFILTER: "(uid=%s)"
      HORUS_LDAP_GROUPFILTER: "(memberUid=%s)"
      HORUSEC_ENABLE_APPLICATION_ADMIN: "false"
      HORUSEC_APPLICATION_ADMIN_DATA: "{\"username\": \"horusec-admin\", \"email\":\"horusec-admin@example.com\", \"password\":\"Devpass0*\"}"
      HORUSEC_AUTH_TYPE: "horusec"
