version: '3'
services:
  postgresql:
    container_name: postgresql
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: horusec_db
    volumes:
      - /var/lib/postgres/db/data:/var/lib/postgresql/data
    tty: true
    logging:
      driver: json-file
      options:
        max-size: 10m
  horusec-account:
    build:
      context: ../../
      dockerfile: ./horusec-account/deployments/Dockerfile
    depends_on:
      - postgresql
    restart: always
    container_name: horusec-account
    ports:
      - "8003:8003"
    environment:
      HORUSEC_ACCOUNT_DISABLE_EMAIL_SERVICE: "true"
      HORUSEC_DATABASE_SQL_URI: "postgresql://root:root@postgresql:5432/horusec_db?sslmode=disable"
      HORUSEC_DATABASE_SQL_DIALECT: "postgres"
      HORUSEC_JWT_SECRET_KEY: "horusec-secret"
      HORUSEC_AUTH_URL: "http://horusec-auth:8006"
