name: HorusecManagerPipeline

on: [push]

jobs:
  install-build-test-fmt-lint:
    name: install-build-test-fmt-lint
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
    - name: Set up Node 12
      uses: actions/setup-node@v1
      with:
        node-version: '12'
      id: node
    - name: Check out code
      uses: actions/checkout@v2
    - name: Install
      run: make install-manager
    - name: Lint
      run: make lint-manager
    - name: build
      run: make build-manager
